Version: 2
Build: 136
Servers: 3
Cpu: "1"
Memory: "1Gi"
Heap: "512M"
Storage: "500M"
ServerPort: 2888
LeaderElectionPort: 3888
ClientPort: 2181

Image: jakkaj/zookeeper:latest
#ImagePullPolicy: "Always"
ImagePullPolicy: "IfNotPresent"
TickTimeMs: 2000
InitTicks: 10
SyncTicks: 5
ClientCnxns: 60
SnapRetain: 3
PurgeHours: 1
ProbeInitialDelaySeconds : 15
ProbeTimeoutSeconds : 5
AntiAffinity: "soft"
LogLevel: "INFO"
MaxSessionTimeout: 40000
MinSessionTimeout: 4000
UpdateStrategy: RollingUpdate
MaxUnavailable: 1